image: node:24

definitions:
  steps:
    - step: &setup-bun
        name: Setup Environment
        caches:
          - node
        script:
          - curl -fsSL https://bun.sh/install | bash
          - source /root/.bashrc
          - bun install --frozen-lockfile
        artifacts:
          - node_modules/**

pipelines:
  branches:
    main:
      - parallel:
          - step:
              <<: *setup-bun
              name: Validations
              script:
                - curl -fsSL https://bun.sh/install | bash
                - source /root/.bashrc
                - bun install --frozen-lockfile
                - bun run lint
                - bun run tsc
          - step:
              <<: *setup-bun
              name: Build
              script:
                - curl -fsSL https://bun.sh/install | bash
                - source /root/.bashrc
                - bun install --frozen-lockfile
                - bun run build:dev
